dataCallback([
  {"ko": "쌀쌀하다", "en": "to be chilly", "zh": "凉飕飕", "vi": "se lạnh", "mn": "сэрүүхэн"},
  {"ko": "포근하다", "en": "to be warm", "zh": "温暖", "vi": "ấm áp", "mn": "дулаахан"},
  {"ko": "날씨가 변덕스럽다", "en": "weather is unpredictable", "zh": "天气多变", "vi": "thời tiết thất thường", "mn": "цаг агаар тогтворгүй"},
  {"ko": "비바람이 불다", "en": "rain and wind are blowing", "zh": "刮风下雨", "vi": "cơn mưa dông", "mn": "салхи шуургатай"},
  {"ko": "일교차가 크다", "en": "temperature changes are drastic", "zh": "温差大", "vi": "chênh lệch nhiệt độ lớn", "mn": "өдөр шөнийн температурын зөрүү их"},
  {"ko": "햇볕이 뜨겁다", "en": "sunshine is hot", "zh": "阳光火辣", "vi": "nắng gắt", "mn": "нар шарах"},
  {"ko": "폭설이 쏟아지다", "en": "snowing heavily", "zh": "下暴雪", "vi": "tuyết rơi dày", "mn": "их цас орох"},
  {"ko": "폭우가 내리다", "en": "raining heavily", "zh": "下暴雨", "vi": "mưa lớn", "mn": "аадар бороо орох"},
  {"ko": "폭염이 계속되다", "en": "heatwave continues", "zh": "酷暑持续", "vi": "nắng nóng kéo dài", "mn": "халуун үргэлжлэх"},
  {"ko": "폭풍이 불다", "en": "storm blows", "zh": "刮暴风", "vi": "bão", "mn": "шуурга шуурах"},
  {"ko": "폭풍우가 치다", "en": "rainstorm is hitting", "zh": "暴风雨来袭", "vi": "bão tố", "mn": "шуурга дэгдэх"},
  {"ko": "선글라스", "en": "sunglasses", "zh": "墨镜", "vi": "kính râm", "mn": "нарны шил"},
  {"ko": "계단", "en": "stairs", "zh": "楼梯", "vi": "cầu thang", "mn": "шат"},
  {"ko": "분실물 센터", "en": "Lost and Found Center", "zh": "失物招领处", "vi": "trung tâm đồ thất lạc", "mn": "гээгдүүлсэн эд зүйлсийн төв"},
  {"ko": "곤란하다", "en": "to be difficult", "zh": "为难", "vi": "khó xử", "mn": "хэцүү"},
  {"ko": "평년", "en": "average year", "zh": "平年", "vi": "năm thường", "mn": "жирийн жил"},
  {"ko": "일교차가 벌어지다", "en": "wide daily temperature difference", "zh": "温差拉大", "vi": "chênh lệch nhiệt độ ngày đêm lớn", "mn": "өдөр шөнийн температурын зөрүү гарах"},
  {"ko": "대비하다", "en": "to prepare", "zh": "准备", "vi": "đối phó, phòng bị", "mn": "бэлдэх"},
  {"ko": "대체로", "en": "mostly", "zh": "大体上", "vi": "nhìn chung", "mn": "ерөнхийдөө"},
  {"ko": "기후", "en": "climate", "zh": "气候", "vi": "khí hậu", "mn": "уур амьсгал"},
  {"ko": "현상", "en": "phenomenon", "zh": "现象", "vi": "hiện tượng", "mn": "үзэгдэл"},
  {"ko": "잠기다", "en": "to be submerged", "zh": "淹没", "vi": "ngập", "mn": "живэх"},
  {"ko": "벌어지다", "en": "to happen", "zh": "发生", "vi": "xảy ra", "mn": "болох"},
  {"ko": "예측하다", "en": "to predict", "zh": "预测", "vi": "dự đoán", "mn": "таамаглах"},
  {"ko": "갑작스럽다", "en": "to be unexpected", "zh": "突然", "vi": "đột ngột", "mn": "гэнэтийн"},
  {"ko": "일부", "en": "some", "zh": "一部分", "vi": "một bộ phận", "mn": "зарим хэсэг"},
  {"ko": "극단적이다", "en": "to be extreme", "zh": "极端的", "vi": "cực đoan", "mn": "туйлын"},
  {"ko": "전문가", "en": "expert", "zh": "专家", "vi": "chuyên gia", "mn": "мэргэжилтэн"},
  {"ko": "절반", "en": "half", "zh": "一半", "vi": "một nửa", "mn": "хагас"},
  {"ko": "가뭄", "en": "drought", "zh": "干旱", "vi": "hạn hán", "mn": "ган"},
  {"ko": "피해", "en": "damage", "zh": "损失", "vi": "thiệt hại", "mn": "хохирол"},
  {"ko": "홍수", "en": "flood", "zh": "洪水", "vi": "lũ lụt", "mn": "үер"},
  {"ko": "폐쇄되다", "en": "to be shut down", "zh": "被关闭", "vi": "bị đóng cửa, bị phong tỏa", "mn": "хаагдах"},
  {"ko": "불편을 겪다", "en": "to experience inconvenience", "zh": "感到不适", "vi": "gặp bất tiện", "mn": "хүндрэл учрах"}
]);