dataCallback([
  {"ko": "쌀쌀하다", "en": "to be chilly", "zh": "凉飕飕", "vi": "se lạnh", "mn": "сэрүүхэн", "ru": "прохладный"},
  {"ko": "포근하다", "en": "to be warm", "zh": "温暖", "vi": "ấm áp", "mn": "дулаахан", "ru": "тёплый"},
  {"ko": "날씨가 변덕스럽다", "en": "weather is unpredictable", "zh": "天气多变", "vi": "thời tiết thất thường", "mn": "цаг агаар тогтворгүй", "ru": "погода переменчива"},
  {"ko": "비바람이 불다", "en": "rain and wind are blowing", "zh": "刮风下雨", "vi": "cơn mưa dông", "mn": "салхи шуургатай", "ru": "дует ветер с дождём"},
  {"ko": "일교차가 크다", "en": "temperature changes are drastic", "zh": "温差大", "vi": "chênh lệch nhiệt độ lớn", "mn": "өдөр шөнийн температурын зөрүү их", "ru": "большая разница температур"},
  {"ko": "햇볕이 뜨겁다", "en": "sunshine is hot", "zh": "阳光火辣", "vi": "nắng gắt", "mn": "нар шарах", "ru": "палящее солнце"},
  {"ko": "폭설이 쏟아지다", "en": "snowing heavily", "zh": "下暴雪", "vi": "tuyết rơi dày", "mn": "их цас орох", "ru": "идёт сильный снег"},
  {"ko": "폭우가 내리다", "en": "raining heavily", "zh": "下暴雨", "vi": "mưa lớn", "mn": "аадар бороо орох", "ru": "идёт сильный дождь"},
  {"ko": "폭염이 계속되다", "en": "heatwave continues", "zh": "酷暑持续", "vi": "nắng nóng kéo dài", "mn": "халуун үргэлжлэх", "ru": "жара продолжается"},
  {"ko": "폭풍이 불다", "en": "storm blows", "zh": "刮暴风", "vi": "bão", "mn": "шуурга шуурах", "ru": "дует шторм"},
  {"ko": "폭풍우가 치다", "en": "rainstorm is hitting", "zh": "暴风雨来袭", "vi": "bão tố", "mn": "шуурга дэгдэх", "ru": "бушует шторм"},
  {"ko": "선글라스", "en": "sunglasses", "zh": "墨镜", "vi": "kính râm", "mn": "нарны шил", "ru": "солнцезащитные очки"},
  {"ko": "계단", "en": "stairs", "zh": "楼梯", "vi": "cầu thang", "mn": "шат", "ru": "лестница"},
  {"ko": "분실물 센터", "en": "Lost and Found Center", "zh": "失物招领处", "vi": "trung tâm đồ thất lạc", "mn": "гээгдүүлсэн эд зүйлсийн төв", "ru": "бюро находок"},
  {"ko": "곤란하다", "en": "to be difficult", "zh": "为难", "vi": "khó xử", "mn": "хэцүү", "ru": "быть в затруднении"},
  {"ko": "평년", "en": "average year", "zh": "平年", "vi": "năm thường", "mn": "жирийн жил", "ru": "обычный год"},
  {"ko": "일교차가 벌어지다", "en": "to have a wide daily temperature difference", "zh": "温差拉大", "vi": "chênh lệch nhiệt độ ngày đêm lớn", "mn": "өдөр шөнийн температурын зөрүү гарах", "ru": "возникает большая разница температур"},
  {"ko": "대비하다", "en": "to prepare", "zh": "准备", "vi": "đối phó, phòng bị", "mn": "бэлдэх", "ru": "готовиться, принимать меры"},
  {"ko": "대체로", "en": "mostly", "zh": "大体上", "vi": "nhìn chung", "mn": "ерөнхийдөө", "ru": "в основном"},
  {"ko": "기후", "en": "climate", "zh": "气候", "vi": "khí hậu", "mn": "уур амьсгал", "ru": "климат"},
  {"ko": "현상", "en": "phenomenon", "zh": "现象", "vi": "hiện tượng", "mn": "үзэгдэл", "ru": "явление"},
  {"ko": "잠기다", "en": "to be submerged", "zh": "淹没", "vi": "ngập", "mn": "живэх", "ru": "быть затопленным"},
  {"ko": "벌어지다", "en": "to happen", "zh": "发生", "vi": "xảy ra", "mn": "болох", "ru": "происходить"},
  {"ko": "예측하다", "en": "to predict", "zh": "预测", "vi": "dự đoán", "mn": "таамаглах", "ru": "предсказывать"},
  {"ko": "갑작스럽다", "en": "to be unexpected", "zh": "突然", "vi": "đột ngột", "mn": "гэнэтийн", "ru": "внезапный"},
  {"ko": "일부", "en": "some", "zh": "一部分", "vi": "một bộ phận", "mn": "зарим хэсэг", "ru": "часть"},
  {"ko": "극단적이다", "en": "to be extreme", "zh": "极端的", "vi": "cực đoan", "mn": "туйлын", "ru": "экстремальный"},
  {"ko": "전문가", "en": "expert", "zh": "专家", "vi": "chuyên gia", "mn": "мэргэжилтэн", "ru": "эксперт"},
  {"ko": "절반", "en": "half", "zh": "一半", "vi": "một nửa", "mn": "хагас", "ru": "половина"},
  {"ko": "가뭄", "en": "drought", "zh": "干旱", "vi": "hạn hán", "mn": "ган", "ru": "засуха"},
  {"ko": "피해", "en": "damage", "zh": "损失", "vi": "thiệt hại", "mn": "хохирол", "ru": "ущерб"},
  {"ko": "홍수", "en": "flood", "zh": "洪水", "vi": "lũ lụt", "mn": "үер", "ru": "наводнение"},
  {"ko": "폐쇄되다", "en": "to be shut down", "zh": "被关闭", "vi": "bị đóng cửa, bị phong tỏa", "mn": "хаагдах", "ru": "быть закрытым"},
  {"ko": "불편을 겪다", "en": "to experience inconvenience", "zh": "感到不适", "vi": "gặp bất tiện", "mn": "хүндрэл учрах", "ru": "испытывать неудобства"},
  {"ko": "건조하다", "en": "to be dry", "zh": "干燥", "vi": "khô", "mn": "хуурай", "ru": "сухой"},
  {"ko": "강수량이 많다 / 적다", "en": "precipitation is high / low", "zh": "降雨量多 / 少", "vi": "lượng mưa nhiều / ít", "mn": "хур тунадас их / бага", "ru": "высокое / низкое количество осадков"},
  {"ko": "습도가 높다", "en": "humidity is high", "zh": "湿度高", "vi": "độ ẩm cao", "mn": "чийгшил ихтэй", "ru": "высокая влажность"},
  {"ko": "서늘하다", "en": "to be cool", "zh": "凉爽", "vi": "mát mẻ", "mn": "сэрүүн", "ru": "прохладный"},
  {"ko": "더위가 / 추위가 심하다", "en": "heat / cold is severe", "zh": "酷暑 / 严寒", "vi": "nóng / lạnh khắc nghiệt", "mn": "халуун / хүйтэн ихтэй", "ru": "сильная жара / сильный холод"},
  {"ko": "사계절이 뚜렷하다", "en": "four seasons are distinct", "zh": "四季分明", "vi": "bốn mùa rõ rệt", "mn": "дөрвөн улирал тод", "ru": "четыре времени года чётко выражены"},
  {"ko": "생소하다", "en": "to be unfamiliar", "zh": "陌生", "vi": "xa lạ, lạ lẫm, mới mẻ", "mn": "танил бус", "ru": "незнакомый"},
  {"ko": "독특하다", "en": "to be unique", "zh": "独特", "vi": "độc đáo", "mn": "өвөрмөц", "ru": "уникальный"},
  {"ko": "친숙하다", "en": "to be familiar", "zh": "熟悉", "vi": "thân thuộc", "mn": "дотно", "ru": "знакомый"},
  {"ko": "차이가 있다", "en": "to have a difference", "zh": "有差异", "vi": "có sự khác biệt", "mn": "ялгаатай", "ru": "есть разница"},
  {"ko": "공통점이 있다", "en": "to have common ground", "zh": "有共同点", "vi": "có điểm chung", "mn": "нийтлэг талтай", "ru": "иметь общее"},
  {"ko": "구조", "en": "structure", "zh": "结构", "vi": "cấu trúc", "mn": "бүтэц", "ru": "структура"},
  {"ko": "북부", "en": "northern", "zh": "北部", "vi": "phía bắc", "mn": "хойд", "ru": "северный"},
  {"ko": "대청", "en": "a large wooden floor", "zh": "大厅", "vi": "đại sảnh (sàn gỗ)", "mn": "том модон шал", "ru": "тэчхон (большой зал)"},
  {"ko": "외양간", "en": "barn", "zh": "牛棚", "vi": "chuồng bò", "mn": "үхрийн саравч", "ru": "хлев"},
  {"ko": "중부", "en": "central", "zh": "中部", "vi": "miền trung", "mn": "төвийн", "ru": "центральная часть"},
  {"ko": "건넌방", "en": "opposite room", "zh": "对面房间", "vi": "phòng đối diện", "mn": "эсрэг талын өрөө", "ru": "комната напротив"},
  {"ko": "창고", "en": "storage", "zh": "仓库", "vi": "nhà kho", "mn": "агуулах", "ru": "склад"},
  {"ko": "남부", "en": "southern", "zh": "南部", "vi": "phía nam", "mn": "өмнөд", "ru": "южный"},
  {"ko": "재배지", "en": "cultivation area", "zh": "栽培地", "vi": "đất trồng trọt, đất canh tác", "mn": "тариалангийн талбай", "ru": "место выращивания"},
  {"ko": "재배하다", "en": "to cultivate", "zh": "栽培", "vi": "trồng trọt", "mn": "тариалах", "ru": "выращивать"},
  {"ko": "수출하다", "en": "to export", "zh": "出口", "vi": "xuất khẩu", "mn": "экспортлох", "ru": "экспортировать"},
  {"ko": "설명문", "en": "expository writing", "zh": "说明文", "vi": "văn bản thuyết minh", "mn": "тайлбар бичиг", "ru": "пояснительный текст"},
  {"ko": "즉", "en": "in other words", "zh": "也就是", "vi": "tức là", "mn": "өөрөөр хэлбэл", "ru": "то есть"},
  {"ko": "산간", "en": "between mountains", "zh": "山间", "vi": "miền núi", "mn": "уулархаг нутаг", "ru": "горный район"},
  {"ko": "고춧가루", "en": "red pepper powder", "zh": "辣椒粉", "vi": "bột ớt", "mn": "улаан чинжүүний нунтаг", "ru": "молотый красный перец"},
  {"ko": "넉넉하다", "en": "to be abundant", "zh": "充裕", "vi": "dồi dào", "mn": "элбэг", "ru": "обильный"},
  {"ko": "관련성", "en": "relation", "zh": "相关性", "vi": "sự liên quan", "mn": "холбоо хамаарал", "ru": "связь"},
  {"ko": "밀", "en": "wheat", "zh": "小麦", "vi": "lúa mì", "mn": "улаан буудай", "ru": "пшеница"},
  {"ko": "보리", "en": "barley", "zh": "大麦", "vi": "lúa mạch", "mn": "арвай", "ru": "ячмень"},
  {"ko": "주식", "en": "staple food", "zh": "主食", "vi": "lương thực chính", "mn": "үндсэн хоол", "ru": "основной продукт питания"}
]);